@host=http://localhost:5169

POST {{host}}/api/AccountTransactions

{
  "accountId": 0,
  "referenceNumber": "string",
  "transactionDate": "2024-01-05T17:15:05.866Z",
  "amount": 0,
  "description": "string",
  "transferType": "string"
}